### ISSUE TITLE
ACNB0

### ISSUE THREAD

**Issue by mkrompiec** [Sassafrass6/PAOFLOW#2]
I am interested in the ACBN0 functional. I tried to run the code from https://github.com/Sassafrass6/PAOFLOW/blob/master/src/externals/acbn0/examples/MgO/scfuj.py, but (apart from some tab/space inconsistencies which were trivial to fix), it seems to need a 'main.py' script for the PAOFLOW part. Where can I find it? Is this the recommended way of running ACBN0 calculations? The documentation says that this code is for Python 2.7, but it seems to be (almost) compatible with Python 3 - can you confirm this?

**Comment by mkrompiec** [comment]
This seems to work as the missing main.py:
from PAOFLOW import PAOFLOW
paoflow = PAOFLOW.PAOFLOW()

**Comment by mkrompiec** [comment]
Well, it doesn't. The PAOFLOW main.py doesn't save any output. Then, acnb0.py trips up with this message:
Reading the PAO data
Traceback (most recent call last):
  File "acbn0.py", line 461, in <module>
    test(fpath,reduced_basis_dm,reduced_basis_2e,latvects,coords,atlabels,outfile)
  File "acbn0.py", line 311, in test
    nkpnts,kpnts,kpnts_wght,Sks,Hks_nospin = read_txtdata(fpath,nspin)
  File "acbn0.py", line 186, in read_txtdata
    fin   = open(fpath+'/'+'wk.txt',"r")
IOError: [Errno 2] No such file or directory: '{cut}/acbn0/src/wk.txt'

But where is the wk.txt (weights of k-points?) file produced? I can't find this anywhere in the PAOFLOW sources.
The next few lines of acbn0.py require the file k.txt which I also do not have.
